### ISSUE TITLE
Telegram::Bot::NotFound (Not Found):

### ISSUE THREAD

**Issue by schekin** [telegram-bot-rb/telegram-bot#106]
```
class TelegramWebhooksController < Telegram::Bot::UpdatesController
  include Telegram::Bot::UpdatesController::MessageContext

  def message(message)
    respond_with :message, text:  "test respond"
  end

  def start(*)
    respond_with :message, text: 'Приветствуем! Для начала работы введите номер Вашего мобильного телефона для авторизации'
  end


  def help!(*)

  end
end

```

app/controllers/telegram_webhooks_controller.rb:5:in `message'
Started POST "/telegram/bot573256176_AAFom7ajHmK_Wu7mivpaw-ZXJBZZuduDYz4" for 149.154.167.213 at 2018-11-13 16:17:06 +0300
Processing by TelegramWebhooksController#message
  Update: {"update_id":80962347,"message":{"message_id":4241,"from":{"id":45199383,"is_bot":false,"first_name":"Pavel","last_name":"iiiwiw","username":"___hekin","language_code":"ru-BY"},"chat":{"id": 45199383,"first_name":"Pavel","last_name":"Schekin","username":"schekin","type":"private"},"date":1542114990,"text":"ss"}}
Responded with message
Completed in 81ms (ActiveRecord: 0.0ms)
  
Telegram::Bot::NotFound (Not Found):
  
app/controllers/telegram_webhooks_controller.rb:5:in `message'

**Comment by schekin** [comment]
Sorry....    I am used invalid token...  bot573256176_AA....
