### ISSUE TITLE
Send media group

### ISSUE THREAD

**Issue by Yegorov** [telegram-bot-rb/telegram-bot#167]
Hello! 
How send [media group](https://core.telegram.org/bots/api#sendmediagroup)?
I try:
```ruby
  bot.send_media_group(
      chat_id: chat_id,
      media: [
          {
            type: 'photo',
            media: File.open(Rails.root.join('app', 'assets', 'images', 'img1.png')),
          },
          {
            type: 'photo',
            media: File.open(Rails.root.join('app', 'assets', 'images', 'img2.jpg')),
          }
        ]
    )
```
but get error:
```
Bad Request: Bad Request: wrong remote file identifier specified: Wrong character in the string                         
/home/artem/.rvm/gems/ruby-3.0.1/gems/telegram-bot-0.15.3/lib/telegram/bot/client.rb:74:in `request'                    
/home/artem/.rvm/gems/ruby-3.0.1/gems/telegram-bot-0.15.3/lib/telegram/bot/async.rb:151:in `request'                    
/home/artem/.rvm/gems/ruby-3.0.1/gems/telegram-bot-0.15.3/lib/telegram/bot/client/api_helper.rb:22:in `block (2 levels) 
in define_helpers'
```

**Comment by printercu** [comment]
Hey! Could you please give it a try:
```ruby
gem 'telegram-bot', github: 'telegram-bot-rb/telegram-bot', branch: 'nested_files'
```

**Comment by Yegorov** [comment]
Hi, @printercu!
Thanks, for fast response. It's work!

**Comment by mario-amazing** [comment]
With current bot logic you can send media_group like this:
```ruby
    response = respond_with :media_group,
      media: [
        { type: 'photo', media: 'attach://menu1' },
        { type: 'photo', media: 'attach://menu2' }
      ],
      menu1: File.open(Rails.root.join('public/images/telegram_bot/menu1.jpg')),
      menu2: File.open(Rails.root.join('public/images/telegram_bot/menu2.jpg'))
```
