### ISSUE TITLE
ArgumentError when using sessions with Redis cache store in Ruby 3.0

### ISSUE THREAD

**Issue by marckohlbrugge** [telegram-bot-rb/telegram-bot#179]
I'm using the session cache store like this:

```ruby
class TelegramWebhooksController < Telegram::Bot::UpdatesController
  include Telegram::Bot::UpdatesController::Session
  self.session_store = :redis_store, {expires_in: 1.month}
end
```

But whenever I use the session, I get the error message below. This seems related to [how Ruby 3 handles keyword arguments differently](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/).

Is this a bug with this gem?

```
vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.6/lib/active_support/cache.rb:786:in `initialize': wrong number of arguments (given 2, expected 1) (ArgumentError)
    from vendor/bundle/ruby/3.0.0/gems/redis-activesupport-5.2.0/lib/active_support/cache/redis_store.rb:85:in `new'
    from vendor/bundle/ruby/3.0.0/gems/redis-activesupport-5.2.0/lib/active_support/cache/redis_store.rb:85:in `block in write'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.6/lib/active_support/cache.rb:726:in `block in instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.6/lib/active_support/notifications.rb:205:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.6/lib/active_support/cache.rb:726:in `instrument'
    from vendor/bundle/ruby/3.0.0/gems/redis-activesupport-5.2.0/lib/active_support/cache/redis_store.rb:81:in `write'
    from vendor/bundle/ruby/3.0.0/gems/telegram-bot-0.15.4/lib/telegram/bot/updates_controller/session.rb:69:in `commit'
    from vendor/bundle/ruby/3.0.0/gems/telegram-bot-0.15.4/lib/telegram/bot/updates_controller/session.rb:24:in `process_action'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.4.6/lib/abstract_controller/base.rb:165:in `process'
    from vendor/bundle/ruby/3.0.0/gems/telegram-bot-0.15.4/lib/telegram/bot/updates_controller.rb:172:in `process'
    from vendor/bundle/ruby/3.0.0/gems/telegram-bot-0.15.4/lib/telegram/bot/updates_controller.rb:161:in `dispatch'
    from vendor/bundle/ruby/3.0.0/gems/telegram-bot-0.15.4/lib/telegram/bot/updates_controller.rb:109:in `dispatch'
    from vendor/bundle/ruby/3.0.0/gems/telegram-bot-0.15.4/lib/telegram/bot/middleware.rb:19:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.4.6/lib/action_dispatch/routing/mapper.rb:20:in `block in <class:Constraints>'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.4.6/lib/action_dispatch/routing/mapper.rb:49:in `serve'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.4.6/lib/action_dispatch/journey/router.rb:50:in `block in serve'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.4.6/lib/action_dispatch/journey/router.rb:32:in `each'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.4.6/lib/action_dispatch/journey/router.rb:32:in `serve'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.4.6/lib/action_dispatch/routing/route_set.rb:842:in `call'
    from vendor/bundle/ruby/3.0.0/gems/rack-attack-6.6.0/lib/rack/attack.rb:103:in `call'
    from vendor/bundle/ruby/3.0.0/gems/rack-host-redirect-1.3.0/lib/rack/host_redirect.rb:18:in `call'
    from vendor/bundle/ruby/3.0.0/gems/rack-attack-6.6.0/lib/rack/attack.rb:127:in `call'
    from vendor/bundle/ruby/3.0.0/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
    from vendor/bundle/ruby/3.0.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
    from vendor/bundle/ruby/3.0.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
    from vendor/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
    from vendor/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
    from vendor/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:40:in `call'
    from vendor/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.4.6/lib/action_dispatch/http/permissions_policy.rb:22:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.4.6/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
    from vendor/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
    from vendor/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.4.6/lib/action_dispatch/middleware/cookies.rb:689:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.4.6/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.6/lib/active_support/callbacks.rb:98:in `run_callbacks'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.4.6/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.4.6/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
    from vendor/bundle/ruby/3.0.0/gems/bugsnag-6.24.2/lib/bugsnag/integrations/rack.rb:51:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.4.6/lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.4.6/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
    from vendor/bundle/ruby/3.0.0/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
    from vendor/bundle/ruby/3.0.0/gems/railties-6.1.4.6/lib/rails/rack/logger.rb:26:in `block in call'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.6/lib/active_support/tagged_logging.rb:99:in `block in tagged'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.6/lib/active_support/tagged_logging.rb:37:in `tagged'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.6/lib/active_support/tagged_logging.rb:99:in `tagged'
    from vendor/bundle/ruby/3.0.0/gems/railties-6.1.4.6/lib/rails/rack/logger.rb:26:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.4.6/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
    from vendor/bundle/ruby/3.0.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
    from vendor/bundle/ruby/3.0.0/gems/rack-timeout-0.6.0/lib/rack/timeout/core.rb:151:in `block in call'
    from vendor/bundle/ruby/3.0.0/gems/rack-timeout-0.6.0/lib/rack/timeout/support/timeout.rb:19:in `timeout'
    from vendor/bundle/ruby/3.0.0/gems/rack-timeout-0.6.0/lib/rack/timeout/core.rb:150:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.4.6/lib/action_dispatch/middleware/request_id.rb:26:in `call'
    from vendor/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
    from vendor/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
    from vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.6/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.4.6/lib/action_dispatch/middleware/executor.rb:14:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.4.6/lib/action_dispatch/middleware/static.rb:24:in `call'
    from vendor/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.4.6/lib/action_dispatch/middleware/ssl.rb:77:in `call'
    from vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.4.6/lib/action_dispatch/middleware/host_authorization.rb:113:in `call'
    from vendor/bundle/ruby/3.0.0/gems/rack-mini-profiler-3.0.0/lib/mini_profiler/profiler.rb:249:in `call'
    from vendor/bundle/ruby/3.0.0/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
    from vendor/bundle/ruby/3.0.0/gems/railties-6.1.4.6/lib/rails/engine.rb:539:in `call'
    from vendor/bundle/ruby/3.0.0/gems/puma-5.6.2/lib/puma/configuration.rb:252:in `call'
    from vendor/bundle/ruby/3.0.0/gems/puma-5.6.2/lib/puma/request.rb:77:in `block in handle_request'
    from vendor/bundle/ruby/3.0.0/gems/puma-5.6.2/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
    from vendor/bundle/ruby/3.0.0/gems/puma-5.6.2/lib/puma/request.rb:76:in `handle_request'
    from vendor/bundle/ruby/3.0.0/gems/puma-5.6.2/lib/puma/server.rb:441:in `process_client'
    from vendor/bundle/ruby/3.0.0/gems/puma-5.6.2/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```

**Comment by marckohlbrugge** [comment]
Never mind. Seems like it was due to one of my redis gems.
