### ISSUE TITLE
Telegram::Bot::Error: Bad Gateway: Bad Gateway

### ISSUE THREAD

**Issue by anko20094** [telegram-bot-rb/telegram-bot#181]
```
"00:41: Started scheduler 'every 10 min'"
"00:41: Everything is fine"
"00:41: Everything is fine"
"00:41: Everything is fine"
"00:41: Everything is fine"
"00:41: Everything is fine"
"00:41: Everything is fine"
"00:51: Started scheduler 'every 10 min'"
"00:51: Everything is fine"
"00:51: Everything is fine"
"00:51: Everything is fine"
"00:51: Everything is fine"
"00:51: Everything is fine"
"00:51: Everything is fine"
rake aborted!
Telegram::Bot::Error: Bad Gateway: Bad Gateway
/usr/local/rvm/gems/ruby-3.0.1/gems/telegram-bot-0.15.6/lib/telegram/bot/client.rb:67:in `request'
/usr/local/rvm/gems/ruby-3.0.1/gems/telegram-bot-0.15.6/lib/telegram/bot/async.rb:151:in `request'
/usr/local/rvm/gems/ruby-3.0.1/gems/telegram-bot-0.15.6/lib/telegram/bot/client/api_helper.rb:22:in `block (2 levels) in define_helpers'
/usr/local/rvm/gems/ruby-3.0.1/gems/telegram-bot-0.15.6/lib/telegram/bot/updates_poller.rb:71:in `block in fetch_updates'
/usr/local/rvm/gems/ruby-3.0.1/gems/telegram-bot-0.15.6/lib/telegram/bot/async.rb:138:in `async'
/usr/local/rvm/gems/ruby-3.0.1/gems/telegram-bot-0.15.6/lib/telegram/bot/updates_poller.rb:71:in `fetch_updates'
/usr/local/rvm/gems/ruby-3.0.1/gems/telegram-bot-0.15.6/lib/telegram/bot/updates_poller.rb:58:in `run'
/usr/local/rvm/gems/ruby-3.0.1/gems/telegram-bot-0.15.6/lib/telegram/bot/updates_poller.rb:47:in `start'
/usr/local/rvm/gems/ruby-3.0.1/gems/telegram-bot-0.15.6/lib/telegram/bot/updates_poller.rb:21:in `start'
```
I have two very simple bots but they at one time down out with the same error. How Is the best to handle this error? Now I'm using(but haven't tested yet) these code:
```
 begin
     check_sites(TelegramWebhooksController::SITES_FOR_CHECK)
 rescue Telegram::Bot::Error => e
     p "#{current_time}: #{e} - exception"
     sleep 60 
     retry
  end
```

**Comment by printercu** [comment]
Yes, this approach will work for you.
