### ISSUE TITLE
undefined method `telegram_webhook_url' for #<Module:0x000055575ce73188>

### ISSUE THREAD

**Issue by Joe-tver** [telegram-bot-rb/telegram-bot#188]
bundle exec rake telegram:bot:set_webhook RAILS_ENV=staging
rake aborted!
NoMethodError: undefined method `telegram_webhook_url' for #<Module:0x000055575ce73188>

**Comment by printercu** [comment]
https://github.com/telegram-bot-rb/telegram-bot#routes-in-rails-app

**Comment by Joe-tver** [comment]
У меян есть в роутере 
telegram_webhook Api::Erp::Telegram::WebhookController

и пробую postman туда отправлять запрос все работает! Но не работает bundle exec rake telegram:bot:set_webhook

**Comment by printercu** [comment]
rails routes какое название у этого маршрута показывает?

**Comment by Joe-tver** [comment]
вывод rails routes:

api_erp_telegram_webhook POST   /api/erp/telegram/bAc0EFIGPgis4wCBES2R0PjZ-MQ                             
#<Telegram::Bot::Middleware(Api::Erp::Telegram::WebhookController)> {:format=>:json}

**Comment by printercu** [comment]
Чтобы рэйк таска работала telegram_webhook должен быть в бещ скоупов, на верхнем уровне

**Comment by Joe-tver** [comment]
Спасибо все заработало!!!

**Comment by kayn23** [comment]
Похожая ситуация. Вызываю `rake telegram:bot:set_webhook RAILS_ENV=production`
Ошибка следующая
```
Setting webhook for default...
rake aborted!
NoMethodError: undefined method `chat_telegram_webhook_url' for #<Module:0x00007f1430f63ad8>

          url = routes.send("#{route_name}_url")
                      ^^^^^
/home/deploy/cryptoguru/shared/bundle/ruby/3.1.0/gems/telegram-bot-0.15.7/lib/telegram/bot/tasks.rb:14:in `block in set_webhook'
/home/deploy/cryptoguru/shared/bundle/ruby/3.1.0/gems/telegram-bot-0.15.7/lib/telegram/bot/tasks.rb:55:in `block (2 levels) in each_bot'
/home/deploy/cryptoguru/shared/bundle/ruby/3.1.0/gems/telegram-bot-0.15.7/lib/telegram/bot/async.rb:138:in `async'
/home/deploy/cryptoguru/shared/bundle/ruby/3.1.0/gems/telegram-bot-0.15.7/lib/telegram/bot/tasks.rb:55:in `block in each_bot'
/home/deploy/cryptoguru/shared/bundle/ruby/3.1.0/gems/telegram-bot-0.15.7/lib/telegram/bot/tasks.rb:55:in `each'
/home/deploy/cryptoguru/shared/bundle/ruby/3.1.0/gems/telegram-bot-0.15.7/lib/telegram/bot/tasks.rb:55:in `each_bot'
/home/deploy/cryptoguru/shared/bundle/ruby/3.1.0/gems/telegram-bot-0.15.7/lib/telegram/bot/tasks.rb:12:in `set_webhook'
/home/deploy/cryptoguru/shared/bundle/ruby/3.1.0/gems/telegram-bot-0.15.7/lib/tasks/telegram-bot.rake:17:in `block (3 levels) in <main>'
Tasks: TOP => telegram:bot:set_webhook
(See full trace by running task with --trace)
```
Вывод rails routes 
```
Controller#Action
                default_telegram_webhook POST   /telegram/5*********                                                          
#<Telegram::Bot::Middleware(TelegramWebhooksController)>
```
Уже не знаю как подступиться
