### ISSUE TITLE
RSpec rails undefined method `request=' error

### ISSUE THREAD

**Issue by mario-amazing** [telegram-bot-rb/telegram-bot#193]
Hi, could you help with Rails configuration?
I have this error:
```ruby
      Failure/Error: @controller.request = @request

      NoMethodError:
        undefined method `request=' for #<TelegramWebhookController:0x00000000007d78>

                  @controller.request = @request
                             ^^^^^^^^^^
```
Current config(the same as in README):
```ruby
require 'rails_helper'
require 'telegram/bot/rspec/integration/rails'

RSpec.describe TelegramWebhookController, telegram_bot: :rails do
  describe '#start!' do
    subject { -> { dispatch_command :start } }
    let(:expected_text) { /#{I18n.t('telegram_webhook.available_commands')}/ }

    it { is_expected.to respond_with_message(expected_text) }
  end
end
```

PS: With this config, everything ok:
```ruby
require 'telegram/bot/updates_controller/rspec_helpers'

RSpec.describe TelegramWebhookController, type: :telegram_bot_controller do
```

**Comment by printercu** [comment]
Hey, what rails/actionpack version is it?

**Comment by mario-amazing** [comment]
actionpack (7.0.4)

**Comment by printercu** [comment]
It looks like this error is not related to the gem. I don't see `@controller.request = @request` in the repo and there are [tests](https://github.com/telegram-bot-rb/telegram-bot/blob/master/spec/integration/requests/default_bot_spec.rb#L5) for dispatch_command that pass.

Could you please share error's stacktrace?

**Comment by mario-amazing** [comment]
```
Run options: include {:locations=>{"./spec/controllers/telegram_webhook_controller_spec.rb"=>[40]}}
F

Failures:

  1) TelegramWebhookController#start!
     Failure/Error: @controller.request = @request

     NoMethodError:
       undefined method `request=' for #<TelegramWebhookController:0x00000000007b98>

                 @controller.request = @request
                            ^^^^^^^^^^
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_controller/test_case.rb:549:in `setup_controller_request_and_response'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-rails-6.0.1/lib/rspec/rails/adapters.rb:111:in `block (2 levels) in setup'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:457:in `instance_exec'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:457:in `instance_exec'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:365:in `run'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:529:in `block in run_owned_hooks_for'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:528:in `each'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:528:in `run_owned_hooks_for'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:615:in `block in run_example_hooks_for'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:614:in `reverse_each'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:614:in `run_example_hooks_for'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:484:in `run'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:505:in `run_before_example'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:261:in `block in run'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:511:in `block in with_around_and_singleton_context_hooks'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:468:in `block in with_around_example_hooks'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:486:in `block in run'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:626:in `block in run_around_example_hooks_for'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:352:in `call'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-rails-6.0.1/lib/rspec/rails/example/controller_example_group.rb:192:in `block (2 levels) in <module:ControllerExampleGroup>'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:457:in `instance_exec'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:457:in `instance_exec'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:390:in `execute_with'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:352:in `call'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-rails-6.0.1/lib/rspec/rails/adapters.rb:75:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:457:in `instance_exec'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:457:in `instance_exec'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:390:in `execute_with'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:352:in `call'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:629:in `run_around_example_hooks_for'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:486:in `run'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:468:in `with_around_example_hooks'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:511:in `with_around_and_singleton_context_hooks'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:259:in `run'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:646:in `block in run_examples'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:642:in `map'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:642:in `run_examples'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:607:in `run'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:608:in `block in run'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:608:in `map'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:608:in `run'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:121:in `map'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/configuration.rb:2070:in `with_suite_hooks'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/reporter.rb:74:in `report'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:115:in `run_specs'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:89:in `run'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:71:in `run'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:45:in `invoke'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rspec-core-3.12.0/exe/rspec:4:in `<top (required)>'
     # /Users/mario/.rbenv/versions/3.1.3/bin/rspec:25:in `load'
     # /Users/mario/.rbenv/versions/3.1.3/bin/rspec:25:in `<top (required)>'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/lib/bundler/cli/exec.rb:58:in `load'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/lib/bundler/cli/exec.rb:23:in `run'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/lib/bundler/cli.rb:483:in `exec'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/lib/bundler/cli.rb:31:in `dispatch'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/lib/bundler/cli.rb:25:in `start'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/exe/bundle:48:in `block in <top (required)>'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
     # /Users/mario/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/exe/bundle:36:in `<top (required)>'
     # /Users/mario/.rbenv/versions/3.1.3/bin/bundle:25:in `load'
     # /Users/mario/.rbenv/versions/3.1.3/bin/bundle:25:in `<main>'
     #
     #   Showing full backtrace because every line was filtered out.
     #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
     #   RSpec::Configuration#backtrace_inclusion_patterns for more information.

Finished in 0.0142 seconds (files took 1.88 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/controllers/telegram_webhook_controller_spec.rb:40 # TelegramWebhookController#start!
```

**Comment by printercu** [comment]
Is TelegramWebhookController inherited from Telegram::Bot::UpdatesController?

**Comment by mario-amazing** [comment]
class TelegramWebhookController < Telegram::Bot::UpdatesController

**Comment by printercu** [comment]
It looks like an issue is in the path: ./spec/controllers/telegram_webhook_controller_spec.rb

rspec-rails automatically runs tests as controller test for files in spec/controller. Test with `telegram_bot: :rails` are request tests and should be placed in `spec/requests`.

**Comment by mario-amazing** [comment]
It works, could you add this detail to the README?

And thank you so much for your help! I really appreciate it
