### ISSUE TITLE
Does gem support providing MarkdownV2 style?

### ISSUE THREAD

**Issue by tagirahmad** [telegram-bot-rb/telegram-bot#211]
It works with 
```ruby
respond_with :message, text: t('.how_lectures.text'), parse_mode: :Markdown
```
but doesn't work with

```ruby
respond_with :message, text: t('.how_lectures.text'), parse_mode: :MarkdownV2
```

Exception is raised:

```
Bad Request: Bad Request: can't parse entities: Character '.' is reserved and must be escaped with the preceding '\'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/telegram-bot-0.15.7/lib/telegram/bot/client.rb:67:in `request'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/telegram-bot-0.15.7/lib/telegram/bot/async.rb:151:in `request'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/telegram-bot-0.15.7/lib/telegram/bot/client/api_helper.rb:22:in `block (2 levels) in define_helpers'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/telegram-bot-0.15.7/lib/telegram/bot/client/typed_response.rb:20:in `block (2 levels) in <module:TypedResponse>'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/telegram-bot-0.15.7/lib/telegram/bot/updates_controller/reply_helpers.rb:13:in `public_send'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/telegram-bot-0.15.7/lib/telegram/bot/updates_controller/reply_helpers.rb:13:in `respond_with'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/telegram-bot-0.15.7/lib/telegram/bot/updates_controller/instrumentation.rb:40:in `block in respond_with'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.5/lib/active_support/notifications.rb:206:in `block in instrument'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.5/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.5/lib/active_support/notifications.rb:206:in `instrument'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/telegram-bot-0.15.7/lib/telegram/bot/updates_controller/instrumentation.rb:15:in `instrument'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/telegram-bot-0.15.7/lib/telegram/bot/updates_controller/instrumentation.rb:40:in `respond_with'
/Users/tagirahmadeev/dev/ruby/my_projects/krujokznaniy/app/controllers/telegram/bot/webhooks/feedbacks_controller.rb:81:in `callback_query'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.0.5/lib/abstract_controller/base.rb:215:in `process_action'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.0.5/lib/abstract_controller/callbacks.rb:234:in `block in process_action'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.5/lib/active_support/callbacks.rb:99:in `run_callbacks'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.0.5/lib/abstract_controller/callbacks.rb:233:in `process_action'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/telegram-bot-0.15.7/lib/telegram/bot/updates_controller/rescue.rb:13:in `process_action'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/telegram-bot-0.15.7/lib/telegram/bot/updates_controller/instrumentation.rb:32:in `block in process_action'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.5/lib/active_support/notifications.rb:206:in `block in instrument'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.5/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.5/lib/active_support/notifications.rb:206:in `instrument'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/telegram-bot-0.15.7/lib/telegram/bot/updates_controller/instrumentation.rb:15:in `instrument'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/telegram-bot-0.15.7/lib/telegram/bot/updates_controller/instrumentation.rb:30:in `process_action'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.0.5/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/telegram-bot-0.15.7/lib/telegram/bot/updates_controller/session.rb:22:in `process_action'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.0.5/lib/abstract_controller/base.rb:151:in `process'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/telegram-bot-0.15.7/lib/telegram/bot/updates_controller.rb:172:in `process'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/telegram-bot-0.15.7/lib/telegram/bot/updates_controller.rb:161:in `dispatch'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/telegram-bot-0.15.7/lib/telegram/bot/updates_controller.rb:109:in `dispatch'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/telegram-bot-0.15.7/lib/telegram/bot/updates_poller.rb:91:in `process_update'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/telegram-bot-0.15.7/lib/telegram/bot/updates_poller.rb:82:in `block (2 levels) in process_updates'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/telegram-bot-0.15.7/lib/telegram/bot/updates_poller.rb:80:in `each'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/telegram-bot-0.15.7/lib/telegram/bot/updates_poller.rb:80:in `block in process_updates'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/telegram-bot-0.15.7/lib/telegram/bot/updates_poller.rb:100:in `block in reload!'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/telegram-bot-0.15.7/lib/telegram/bot/updates_poller.rb:107:in `block in reloading_code'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.5/lib/active_support/execution_wrapper.rb:92:in `wrap'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.5/lib/active_support/reloader.rb:72:in `block in wrap'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.5/lib/active_support/execution_wrapper.rb:92:in `wrap'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.5/lib/active_support/reloader.rb:71:in `wrap'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/telegram-bot-0.15.7/lib/telegram/bot/updates_poller.rb:106:in `reloading_code'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/telegram-bot-0.15.7/lib/telegram/bot/updates_poller.rb:96:in `reload!'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/telegram-bot-0.15.7/lib/telegram/bot/updates_poller.rb:79:in `process_updates'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/telegram-bot-0.15.7/lib/telegram/bot/updates_poller.rb:59:in `run'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/telegram-bot-0.15.7/lib/telegram/bot/updates_poller.rb:47:in `start'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/telegram-bot-0.15.7/lib/telegram/bot/updates_poller.rb:21:in `start'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/telegram-bot-0.15.7/lib/tasks/telegram-bot.rake:12:in `block (3 levels) in <main>'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/tagirahmadeev/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
bin/rake:4:in `<main>'
```

**Comment by printercu** [comment]
Bot doesn't provide support for any particular parsing. These options are passed through to telegram api, and error you get us from tg api.

**Comment by tagirahmad** [comment]
Do you mean that even providing `parse_mode: :Markdown` is not supported?

> Bot doesn't provide support for any particular parsing. These options are passed through to telegram api, and error you get us from tg api.

**Comment by printercu** [comment]
I mean that gem doesn't care about what parse_mode is passed. Telegram does the parsing.

**Comment by printercu** [comment]
`can't parse entities: Character '.' is reserved and must be escaped with the preceding '\'` this error is returned by telegram. It looks like you pass invalid MarkdownV2 text. You will get the same error if you send same request without using this gem.

**Comment by tagirahmad** [comment]
Weird. So official MarkdownV2 doesn't work..
https://core.telegram.org/bots/api#markdownv2-style

**Comment by printercu** [comment]
From the link you provided:

> In all other places characters '_', '*', '[', ']', '(', ')', '~', '`', '>', '#', '+', '-', '=', '|', '{', '}', '.', '!' must be escaped with the preceding character '\'.

Does your message match this retirement?
