### ISSUE TITLE
Auto-register webhook callback URL at server start?

### ISSUE THREAD

**Issue by SummitCollie** [telegram-bot-rb/telegram-bot#244]
Hey, I've been developing a bot using the poller locally and it's worked fine, but now I'm trying to put it on a production server in async mode. I added an initializer to call the webhook registration rake task (so I don't have to run it manually) and I'm running into this error:

```ruby
# config/initializers/telegram_bot.rb
Rake::Task['telegram:bot:set_webhook'].invoke if Rails.env.production?
```

```
bin/rails aborted!
Define ApplicationJob class or setup #async= with custom job class
/app/vendor/bundle/ruby/3.3.0/gems/telegram-bot-0.16.3/lib/telegram/bot/async.rb:61:in `rescue in default_async_job'
/app/vendor/bundle/ruby/3.3.0/gems/telegram-bot-0.16.3/lib/telegram/bot/async.rb:58:in `default_async_job'
/app/vendor/bundle/ruby/3.3.0/gems/telegram-bot-0.16.3/lib/telegram/bot/async.rb:89:in `prepare_async_val'
/app/vendor/bundle/ruby/3.3.0/gems/telegram-bot-0.16.3/lib/telegram/bot/async.rb:125:in `async='
/app/vendor/bundle/ruby/3.3.0/gems/telegram-bot-0.16.3/lib/telegram/bot/async.rb:118:in `initialize'
/app/vendor/bundle/ruby/3.3.0/gems/telegram-bot-0.16.3/lib/telegram/bot/client.rb:27:in `new'
/app/vendor/bundle/ruby/3.3.0/gems/telegram-bot-0.16.3/lib/telegram/bot/client.rb:27:in `wrap'
/app/vendor/bundle/ruby/3.3.0/gems/telegram-bot-0.16.3/lib/telegram/bot/config_methods.rb:32:in `block in bots'
/app/vendor/bundle/ruby/3.3.0/gems/telegram-bot-0.16.3/lib/telegram/bot/config_methods.rb:31:in `each'
/app/vendor/bundle/ruby/3.3.0/gems/telegram-bot-0.16.3/lib/telegram/bot/config_methods.rb:31:in `each_with_object'
/app/vendor/bundle/ruby/3.3.0/gems/telegram-bot-0.16.3/lib/telegram/bot/config_methods.rb:31:in `bots'
/app/vendor/bundle/ruby/3.3.0/gems/telegram-bot-0.16.3/lib/telegram/bot/tasks.rb:54:in `each_bot'
/app/vendor/bundle/ruby/3.3.0/gems/telegram-bot-0.16.3/lib/telegram/bot/tasks.rb:12:in `set_webhook'
/app/vendor/bundle/ruby/3.3.0/gems/telegram-bot-0.16.3/lib/tasks/telegram-bot.rake:23:in `block (3 levels) in <main>'
/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `block in execute'
/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `each'
/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `execute'
/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:199:in `synchronize'
/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/app/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:188:in `invoke'
/app/config/initializers/telegram_bot.rb:22:in `<main>'

... snip ...

Caused by:
NameError: uninitialized constant Telegram::Bot::Async::ClassMethods::ApplicationJob (NameError)
              ApplicationJob
              ^^^^^^^^^^^^^^
/app/vendor/bundle/ruby/3.3.0/gems/telegram-bot-0.16.3/lib/telegram/bot/async.rb:59:in `default_async_job'
/app/vendor/bundle/ruby/3.3.0/gems/telegram-bot-0.16.3/lib/telegram/bot/async.rb:89:in `prepare_async_val'
/app/vendor/bundle/ruby/3.3.0/gems/telegram-bot-0.16.3/lib/telegram/bot/async.rb:125:in `async='
/app/vendor/bundle/ruby/3.3.0/gems/telegram-bot-0.16.3/lib/telegram/bot/async.rb:118:in `initialize'
/app/vendor/bundle/ruby/3.3.0/gems/telegram-bot-0.16.3/lib/telegram/bot/client.rb:27:in `new'
```

What am I doing wrong? My rails app is configured like so:

```ruby
# config/application.rb
config.active_job.queue_adapter = :async
```

And I have an `ApplicationJob` defined:

```ruby
# app/jobs/application_job.rb

class ApplicationJob < ActiveJob::Base
  # Automatically retry jobs that encountered a deadlock
  retry_on ActiveRecord::Deadlocked

  # Most jobs are safe to ignore if the underlying records are no longer available
  discard_on ActiveJob::DeserializationError
end
```

Should I not be doing that in the initializer? If not, then where could it go? I guess worst case I could call it manually :(

Thanks in advance for any advice!

**Comment by SummitCollie** [comment]
Okay I solved it! I needed to check that rails server was defined as well as running after routes were set:

```ruby
# config/application.rb

if Rails.env.production? && defined?(Rails::Server)
  config.after_routes_loaded do
    Rails.application.load_tasks
    Rake::Task['telegram:bot:set_webhook'].invoke
  end
end
```
