### ISSUE TITLE
HTTPClient::ReceiveTimeoutError: execution expired

### ISSUE THREAD

**Issue by DanielRoig** [telegram-bot-rb/telegram-bot#245]
The bot stops to run after some inactivity time

<img width="766" alt="image" src="https://github.com/user-attachments/assets/5465808e-60d0-4241-92f8-41a21cdf0cee">

**Comment by printercu** [comment]
please share full stacktrace

**Comment by DanielRoig** [comment]
![image](https://github.com/user-attachments/assets/645d90dd-504b-4713-b09d-a789f0a95b10)

**Comment by nofxx** [comment]
Getting a timeout after inactivity too, will figure out some retry thing and come back if it works...


`HTTPClient::ReceiveTimeoutError: execution expired (HTTPClient::ReceiveTimeoutError)
/home/nofxx/.local/share/gem/ruby/3.4.0/gems/httpclient-2.9.0/lib/httpclient/ssl_socket.rb:62:in 'HTTPClient::SSLSocket#gets'
/home/nofxx/.local/share/gem/ruby/3.4.0/gems/httpclient-2.9.0/lib/httpclient/session.rb:805:in 'block in HTTPClient::Session#parse_header'
/home/nofxx/.local/share/gem/ruby/3.4.0/gems/timeout-0.4.3/lib/timeout.rb:185:in 'block in Timeout.timeout'
/home/nofxx/.local/share/gem/ruby/3.4.0/gems/timeout-0.4.3/lib/timeout.rb:192:in 'Timeout.timeout'
/home/nofxx/.local/share/gem/ruby/3.4.0/gems/httpclient-2.9.0/lib/httpclient/session.rb:801:in 'HTTPClient::Session#parse_header'
/home/nofxx/.local/share/gem/ruby/3.4.0/gems/httpclient-2.9.0/lib/httpclient/session.rb:784:in 'HTTPClient::Session#read_header'
/home/nofxx/.local/share/gem/ruby/3.4.0/gems/httpclient-2.9.0/lib/httpclient/session.rb:561:in 'HTTPClient::Session#get_header'
/home/nofxx/.local/share/gem/ruby/3.4.0/gems/httpclient-2.9.0/lib/httpclient.rb:1303:in 'HTTPClient#do_get_header'
/home/nofxx/.local/share/gem/ruby/3.4.0/gems/httpclient-2.9.0/lib/httpclient.rb:1249:in 'HTTPClient#do_get_block'
/home/nofxx/.local/share/gem/ruby/3.4.0/gems/httpclient-2.9.0/lib/httpclient.rb:1023:in 'block in HTTPClient#do_request'
/home/nofxx/.local/share/gem/ruby/3.4.0/gems/httpclient-2.9.0/lib/httpclient.rb:1137:in 'HTTPClient#protect_keep_alive_disconnected'
/home/nofxx/.local/share/gem/ruby/3.4.0/gems/httpclient-2.9.0/lib/httpclient.rb:1018:in 'HTTPClient#do_request'
/home/nofxx/.local/share/gem/ruby/3.4.0/gems/httpclient-2.9.0/lib/httpclient.rb:860:in 'HTTPClient#request'
/home/nofxx/.local/share/gem/ruby/3.4.0/gems/httpclient-2.9.0/lib/httpclient.rb:769:in 'HTTPClient#post'
/home/nofxx/.local/share/gem/ruby/3.4.0/gems/telegram-bot-0.16.7/lib/telegram/bot/client.rb:77:in 'Telegram::Bot::Client#http_request'
/home/nofxx/.local/share/gem/ruby/3.4.0/gems/telegram-bot-0.16.7/lib/telegram/bot/client.rb:68:in 'Telegram::Bot::Client#request'
/home/nofxx/.local/share/gem/ruby/3.4.0/gems/telegram-bot-0.16.7/lib/telegram/bot/async.rb:153:in 'Telegram::Bot::Async#request'
/home/nofxx/.local/share/gem/ruby/3.4.0/gems/telegram-bot-0.16.7/lib/telegram/bot/client/api_helper.rb:24:in 'block (2 levels) in Telegram::Bot::Client::ApiHelper#define_helpers'
/home/nofxx/.local/share/gem/ruby/3.4.0/gems/telegram-bot-0.16.7/lib/telegram/bot/updates_poller.rb:73:in 'block in Telegram::Bot::UpdatesPoller#fetch_updates'
/home/nofxx/.local/share/gem/ruby/3.4.0/gems/telegram-bot-0.16.7/lib/telegram/bot/async.rb:140:in 'Telegram::Bot::Async#async'
/home/nofxx/.local/share/gem/ruby/3.4.0/gems/telegram-bot-0.16.7/lib/telegram/bot/updates_poller.rb:73:in 'Telegram::Bot::UpdatesPoller#fetch_updates'
/home/nofxx/.local/share/gem/ruby/3.4.0/gems/telegram-bot-0.16.7/lib/telegram/bot/updates_poller.rb:60:in 'Telegram::Bot::UpdatesPoller#run'
/home/nofxx/.local/share/gem/ruby/3.4.0/gems/telegram-bot-0.16.7/lib/telegram/bot/updates_poller.rb:49:in 'Telegram::Bot::UpdatesPoller#start'
/home/nofxx/.local/share/gem/ruby/3.4.0/gems/telegram-bot-0.16.7/lib/telegram/bot/updates_poller.rb:23:in 'Telegram::Bot::UpdatesPoller.start'
/home/nofxx/.local/share/gem/ruby/3.4.0/gems/telegram-bot-0.16.7/lib/tasks/telegram-bot.rake:21:in 'block (3 levels) in <main>'
Tasks: TOP => telegram:bot:poller
(See full trace by running task with --trace)`
