### ISSUE TITLE
RSpec Integration for multiple bots project

### ISSUE THREAD

**Issue by arsoedjono** [telegram-bot-rb/telegram-bot#29]
Hi there, I want to ask is there any example of how to use the RSpec testing within a project with multiple bots inside it.

For now, I have a project using multiple bots definition in `secrets.yml` but yet I defined just one bot inside it. Like this:

```yaml
test:
  secret_key_base: <string>
  telegram:
    bots:
      mybot:
        token: <bot_token>
        username: <bot_uname>
```

I followed the RSpec example inside your [example app](https://github.com/telegram-bot-rb/telegram_bot_app). Here is my spec file:

```ruby
RSpec.describe TelegramBot::MyBotController, :telegram_bot do
  let(:prefix) { 'telegram_bot.mybot' }

  describe '#start' do
    subject { -> { dispatch_command :start } }
    it { should respond_with_message I18n.t("#{prefix}.start") }
  end
end
```

But yet, when I run the `rspec` it got the following error:

```
TelegramBot::MyBotController#start should send telegram message "Template string"
Failure/Error: it { should respond_with_message I18n.t("#{prefix}.start") }

NoMethodError:
  undefined method `requests' for nil:NilClass
# /Users/arsoedjono/.rvm/gems/ruby-2.3.0/gems/telegram-bot-0.11.3/lib/telegram/bot/rspec/client_matchers.rb:73:in `matches?'
# ./spec/telegram_bots/mybot_spec.rb:6:in `block (3 levels) in <top (required)>'
```

Is it not yet supported for multiple bots project? Or is there any alternatives I could use? I am looking forward to the answer, coz this gem is awesome and I like it.

Best regards

**Comment by printercu** [comment]
Hi! Seems like you just need to add `let(:bot) { Telegram.bots[:mybot] }`. `respond_with_message` is just a shortcut for `send_telegram_message` which implicitly use this bot (which is default to `Telegram.bot`).

If you have interaction with multiple bots within same action/controller, you should use `send_telegram_message/make_telegram_request` matchers and pass the bot explicitly.

**Comment by printercu** [comment]
`#bot` inside integration test is also used to define `#controller_path` (see line 6 in integration.rb). You may want to set it yourself if you have something complex with multiple bots and single controller.

**Comment by arsoedjono** [comment]
Ahh, thanks @printercu, `let(:bot) { Telegram.bots[:mybot] }` works and I don't get the error message again. And more importantly, the specs should be inside `spec/requests` folder because it is using `post` method #TIL.

But, I want to ask another thing, what about the `config.after { Telegram.bot.reset }`? I declared it inside `rails_helper.rb` and got this error:

```
Failure/Error: config.after { Telegram.bot.reset }

NoMethodError:
  undefined method `reset' for nil:NilClass
  Did you mean?  present?
# ./spec/rails_helper.rb:60:in `block (2 levels) in <top (required)>'
```

**Comment by printercu** [comment]
Uh, yes. You have to use `Telegram.bots.each_value(&:reset)` instead. Will add note to readme.

I think I need to raise `Bot is not configured` on access to `Telegram.bot` without having config for it :)

**Comment by arsoedjono** [comment]
Thanks @printercu, so far it all works well by replacing it with `Telegram.bots.each_value(&:reset)`. Looking forward to the update.

Best regards.
