### ISSUE TITLE
Bot not configured

### ISSUE THREAD

**Issue by arsoedjono** [telegram-bot-rb/telegram-bot#51]
Hi @printercu, I am using Heroku to deploy my new app, when I were attempting to deploy it I got an error like this:

```
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        rake aborted!
remote:        Telegram::Bot::Client :benny not configured
remote:        /tmp/build_0e15efd91b39858d4bff32e7fd9896a6/vendor/bundle/ruby/2.4.0/gems/telegram-bot-0.12.1/lib/telegram/bot/initializers.rb:7:in `wrap'
remote:        /tmp/build_0e15efd91b39858d4bff32e7fd9896a6/vendor/bundle/ruby/2.4.0/gems/telegram-bot-0.12.1/lib/telegram/bot/routes_helper.rb:54:in `block in telegram_webhooks'
remote:        /tmp/build_0e15efd91b39858d4bff32e7fd9896a6/vendor/bundle/ruby/2.4.0/gems/telegram-bot-0.12.1/lib/telegram/bot/routes_helper.rb:53:in `each'
remote:        /tmp/build_0e15efd91b39858d4bff32e7fd9896a6/vendor/bundle/ruby/2.4.0/gems/telegram-bot-0.12.1/lib/telegram/bot/routes_helper.rb:53:in `telegram_webhooks'
remote:        /tmp/build_0e15efd91b39858d4bff32e7fd9896a6/config/routes.rb:4:in `block in <top (required)>'
```

Here is my `routes.rb`:

```ruby
# frozen_string_literal: true

Rails.application.routes.draw do
  telegram_webhooks benny: TelegramBot::BennyController
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
```

It runs well when using `rake telegram:bot:poller` at my development (local) environment. Did I do anything wrong?

**Comment by printercu** [comment]
Hi! Have you configured it in secrets.yml?

**Comment by arsoedjono** [comment]
ah shoot, I got wrong syntax in my `secrets.yml`, sorry for bothering @printercu
