### ISSUE TITLE
Redis store options always connects to localhost

### ISSUE THREAD

**Issue by top4ek** [telegram-bot-rb/telegram-bot#67]
Is there any option in config.telegram_updates_controller.session_store to set redis server connection parameters? It's always trying to connect to 127.0.0.1:6379. Or i missed smth?

**Comment by printercu** [comment]
Does this work https://github.com/redis-store/redis-store/wiki/Frameworks-Configuration
?

New rails has its own redis store, i hope its docs can be found in api.rubyonrails.org

**Comment by top4ek** [comment]
yea, i've tried that and some random variants — doesn't helps. I have redis at localhost in development env and all works well, but when I change env to production with `config.session_store :redis_store, servers: ["#{Rails.application.secrets.redis_url}/session"], expires_in: 1.week` it stiil trying to connect to 127.0.0.1, but `redis_url` points to different addres

I know about 5.2, but unfortunately it's not released yet.

**Comment by printercu** [comment]
Does ActiveSupport::Cache.lookup_store creates valid store with custom url?

**Comment by top4ek** [comment]
No, even in dev mode. I've changed URL too.
```
[4] pry(#<TelegramWebhooksController>)> Demobot::Application.config.cache_store = :redis_store, "#{Rails.application.secrets.redis_url}/cache", { expires_in: 90.minutes }
=> [:redis_store, "redis://127.0.1.1:6379/3/cache", {:expires_in=>90 minutes}]
[5] pry(#<TelegramWebhooksController>)> Demobot::Application.config.session_store :redis_store, servers: ["#{Rails.application.secrets.redis_url}/session"], expires_in: 1.week
=> {:servers=>["redis://127.0.1.1:6379/3/session"], :expires_in=>1 week}
[6] pry(#<TelegramWebhooksController>)> Demobot::Application.config.telegram_updates_controller.session_store = :redis_store, { servers: ["#{Rails.application.secrets.redis_url}/session"], expires_in: 1.month }
=> [:redis_store,
 {:servers=>["redis://127.0.1.1:6379/3/session"], :expires_in=>1 month}]
[7] pry(#<TelegramWebhooksController>)> ActiveSupport::Cache.lookup_store
=> <#ActiveSupport::Cache::MemoryStore entries=0, size=0, options={}>
[8] pry(#<TelegramWebhooksController>)> Rails.application.secrets.redis_url
=> "redis://127.0.1.1:6379/3"
```

**Comment by top4ek** [comment]
No, it's empty

```
I, [2018-03-18T09:27:55.400216 #5]  INFO -- : <#ActiveSupport::Cache::MemoryStore entries=0, size=0, options={}>
app_1                | I, [2018-03-18T09:27:55.400731 #5]  INFO -- : "redis://redis:6379/3"
```
Result of this initializer:
```
Demobot::Application.config.cache_store = :redis_store, "#{Rails.application.secrets.redis_url}/cache", { expires_in: 90.minutes }
Demobot::Application.config.session_store :redis_store, servers: ["#{Rails.application.secrets.redis_url}/session"], expires_in: 1.week
Demobot::Application.config.telegram_updates_controller.session_store = :redis_store, { servers: ["#{Rails.application.secrets.redis_url}/session"], expires_in: 1.month }
Rails.logger ActiveSupport::Cache.lookup_store.inspect
Rails.logger Rails.application.secrets.redis_url.inspect
```

**Comment by printercu** [comment]
```
> ActiveSupport::Cache.lookup_store :redis_store, host: 'asd'
=> #<ActiveSupport::Cache::RedisStore:0x007ffa2db4bca0 @data=#<Redis client v4.0.1 for redis://asd:6379/0>, @options={:host=>"asd"}>
```

`host` option seems to work fine. I remember there was separate gem for redis-sentinel setup.

**Comment by top4ek** [comment]
So i've tested some variants and when I just add `config.session_store :redis_store, servers: ["#{Rails.application.secrets.redis_url}/session"], expires_in: 1.week` fails not app itself or gem but puma as I see in stacktrace. It happens when i try to fetch root url, not even `/telegram` endpoint.
```
app_1                | I, [2018-03-19T10:16:46.133892 #5]  INFO -- : [b606dcc0-e488-4d4b-8541-e5afd9862c6f] Started GET "/" for 109.184.88.111 at 2018-03-19 10:16:46 +0000
app_1                | F, [2018-03-19T10:16:46.146598 #5] FATAL -- : [b606dcc0-e488-4d4b-8541-e5afd9862c6f]   
app_1                | F, [2018-03-19T10:16:46.147515 #5] FATAL -- : [b606dcc0-e488-4d4b-8541-e5afd9862c6f] Redis::CannotConnectError (Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)):
app_1                | F, [2018-03-19T10:16:46.147873 #5] FATAL -- : [b606dcc0-e488-4d4b-8541-e5afd9862c6f]   
app_1                | F, [2018-03-19T10:16:46.148152 #5] FATAL -- : [b606dcc0-e488-4d4b-8541-e5afd9862c6f] redis (4.0.1) lib/redis/client.rb:344:in `rescue in establish_connection'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] redis (4.0.1) lib/redis/client.rb:328:in `establish_connection'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] redis (4.0.1) lib/redis/client.rb:99:in `block in connect'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] redis (4.0.1) lib/redis/client.rb:291:in `with_reconnect'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] redis (4.0.1) lib/redis/client.rb:98:in `connect'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] redis (4.0.1) lib/redis/client.rb:363:in `ensure_connected'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] redis (4.0.1) lib/redis/client.rb:219:in `block in process'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] redis (4.0.1) lib/redis/client.rb:304:in `logging'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] redis (4.0.1) lib/redis/client.rb:218:in `process'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] redis (4.0.1) lib/redis/client.rb:118:in `call'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] redis (4.0.1) lib/redis.rb:819:in `block in setnx'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] redis (4.0.1) lib/redis.rb:45:in `block in synchronize'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] /usr/local/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] redis (4.0.1) lib/redis.rb:45:in `synchronize'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] redis (4.0.1) lib/redis.rb:818:in `setnx'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] redis-store (1.4.1) lib/redis/store/interface.rb:13:in `setnx'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] redis-store (1.4.1) lib/redis/store/ttl.rb:16:in `setnx'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] redis-store (1.4.1) lib/redis/store/serialization.rb:9:in `block in setnx'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] redis-store (1.4.1) lib/redis/store/serialization.rb:39:in `_marshal'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] redis-store (1.4.1) lib/redis/store/serialization.rb:9:in `setnx'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] redis-store (1.4.1) lib/redis/store/namespace.rb:15:in `block in setnx'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] redis-store (1.4.1) lib/redis/store/namespace.rb:88:in `namespace'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] redis-store (1.4.1) lib/redis/store/namespace.rb:15:in `setnx'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] redis-rack (2.0.4) lib/rack/session/redis.rb:39:in `block (2 levels) in generate_unique_sid'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] redis-rack (2.0.4) lib/rack/session/redis.rb:94:in `with'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] redis-rack (2.0.4) lib/rack/session/redis.rb:38:in `block in generate_unique_sid'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] redis-rack (2.0.4) lib/rack/session/redis.rb:36:in `loop'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] redis-rack (2.0.4) lib/rack/session/redis.rb:36:in `generate_unique_sid'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] redis-rack (2.0.4) lib/rack/session/redis.rb:52:in `block in get_session'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] redis-rack (2.0.4) lib/rack/session/redis.rb:79:in `with_lock'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] redis-rack (2.0.4) lib/rack/session/redis.rb:49:in `get_session'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] rack (2.0.4) lib/rack/session/abstract/id.rb:425:in `find_session'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] rack (2.0.4) lib/rack/session/abstract/id.rb:280:in `load_session'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] actionpack (5.1.5) lib/action_dispatch/middleware/session/abstract_store.rb:44:in `block in load_session'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] actionpack (5.1.5) lib/action_dispatch/middleware/session/abstract_store.rb:52:in `stale_session_check!'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] actionpack (5.1.5) lib/action_dispatch/middleware/session/abstract_store.rb:44:in `load_session'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] actionpack (5.1.5) lib/action_dispatch/request/session.rb:216:in `load!'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] actionpack (5.1.5) lib/action_dispatch/request/session.rb:212:in `load_for_write!'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] actionpack (5.1.5) lib/action_dispatch/request/session.rb:197:in `merge!'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] actionpack (5.1.5) lib/action_dispatch/request/session.rb:17:in `create'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] actionpack (5.1.5) lib/action_dispatch/middleware/session/abstract_store.rb:70:in `prepare_session'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] rack (2.0.4) lib/rack/session/abstract/id.rb:231:in `context'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] rack (2.0.4) lib/rack/session/abstract/id.rb:226:in `call'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] rack (2.0.4) lib/rack/etag.rb:25:in `call'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] rack (2.0.4) lib/rack/conditional_get.rb:25:in `call'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] rack (2.0.4) lib/rack/head.rb:12:in `call'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] rack (2.0.4) lib/rack/session/abstract/id.rb:232:in `context'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] rack (2.0.4) lib/rack/session/abstract/id.rb:226:in `call'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] actionpack (5.1.5) lib/action_dispatch/middleware/cookies.rb:613:in `call'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] actionpack (5.1.5) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] activesupport (5.1.5) lib/active_support/callbacks.rb:97:in `run_callbacks'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] actionpack (5.1.5) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] actionpack (5.1.5) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] actionpack (5.1.5) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] railties (5.1.5) lib/rails/rack/logger.rb:36:in `call_app'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] railties (5.1.5) lib/rails/rack/logger.rb:24:in `block in call'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] activesupport (5.1.5) lib/active_support/tagged_logging.rb:69:in `block in tagged'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] activesupport (5.1.5) lib/active_support/tagged_logging.rb:26:in `tagged'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] activesupport (5.1.5) lib/active_support/tagged_logging.rb:69:in `tagged'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] railties (5.1.5) lib/rails/rack/logger.rb:24:in `call'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] actionpack (5.1.5) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] actionpack (5.1.5) lib/action_dispatch/middleware/request_id.rb:25:in `call'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] rack (2.0.4) lib/rack/method_override.rb:22:in `call'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] rack (2.0.4) lib/rack/runtime.rb:22:in `call'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] activesupport (5.1.5) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] actionpack (5.1.5) lib/action_dispatch/middleware/executor.rb:12:in `call'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] rack (2.0.4) lib/rack/sendfile.rb:111:in `call'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] honeybadger (3.3.0) lib/honeybadger/rack/error_notifier.rb:33:in `block in call'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] honeybadger (3.3.0) lib/honeybadger/agent.rb:337:in `with_rack_env'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] honeybadger (3.3.0) lib/honeybadger/rack/error_notifier.rb:30:in `call'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] honeybadger (3.3.0) lib/honeybadger/rack/user_feedback.rb:31:in `call'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] honeybadger (3.3.0) lib/honeybadger/rack/user_informer.rb:21:in `call'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] railties (5.1.5) lib/rails/engine.rb:522:in `call'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] puma (3.11.3) lib/puma/configuration.rb:225:in `call'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] puma (3.11.3) lib/puma/server.rb:624:in `handle_request'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] puma (3.11.3) lib/puma/server.rb:438:in `process_client'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] puma (3.11.3) lib/puma/server.rb:302:in `block in run'
app_1                | [b606dcc0-e488-4d4b-8541-e5afd9862c6f] puma (3.11.3) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

Besides, i've tried 5.2 rails. After minimal configuration app gives `Telegram::Bot::Client :default not configured`

**Comment by printercu** [comment]
Why do you pass `servers` instead of `host`? Is it from some docs?

Rails 5.2 uses credentials instead of secrets, I've not used them yet. You can find more info in #60

**Comment by top4ek** [comment]
I've found problem: App was generated with `--api` option and this doesn't contain sessions mechanism by default. So you need to add middleware manually or build app without `--api` option.

Thanks for help.

**Comment by printercu** [comment]
Bots controller does not use session middleware, it works completely different (details in "Session" section in readme).

Anyway it's cool that you've solved this problem.

**Comment by top4ek** [comment]
Yes, but puma failing in this case.
