### ISSUE TITLE
Don't work edit_message

### ISSUE THREAD

**Issue by boggddan** [telegram-bot-rb/telegram-bot#80]
I used: Rails 5.2, gem telegram-bot 0.13.0
If I sent edit_message,  appeared error

```ruby
 def message(*)
     edit_message( :text, text: 'Test' )
  end
```

```
Can not edit message without `inline_message_id` or `message`
/coins/gems/gems/telegram-bot-0.13.0/lib/telegram/bot/updates_controller/reply_helpers.rb:50:in `edit_message'
/coins/app/controllers/telegram/webhook_controller.rb:23:in `message'
/coins/gems/gems/actionpack-5.2.0/lib/abstract_controller/base.rb:194:in `process_action'
/coins/gems/gems/actionpack-5.2.0/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/coins/gems/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:98:in `run_callbacks'
/coins/gems/gems/actionpack-5.2.0/lib/abstract_controller/callbacks.rb:41:in `process_action'
/coins/gems/gems/telegram-bot-0.13.0/lib/telegram/bot/updates_controller/rescue.rb:13:in `process_action'
/coins/gems/gems/telegram-bot-0.13.0/lib/telegram/bot/updates_controller/instrumentation.rb:32:in `block in process_action'
/coins/gems/gems/activesupport-5.2.0/lib/active_support/notifications.rb:168:in `block in instrument'
/coins/gems/gems/activesupport-5.2.0/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/coins/gems/gems/activesupport-5.2.0/lib/active_support/notifications.rb:168:in `instrument'
/coins/gems/gems/telegram-bot-0.13.0/lib/telegram/bot/updates_controller/instrumentation.rb:15:in `instrument'
/coins/gems/gems/telegram-bot-0.13.0/lib/telegram/bot/updates_controller/instrumentation.rb:30:in `process_action'
/coins/gems/gems/activerecord-5.2.0/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
/coins/gems/gems/telegram-bot-0.13.0/lib/telegram/bot/updates_controller/session.rb:22:in `process_action'
/coins/gems/gems/actionpack-5.2.0/lib/abstract_controller/base.rb:134:in `process'
/coins/gems/gems/telegram-bot-0.13.0/lib/telegram/bot/updates_controller.rb:172:in `dispatch'
/coins/gems/gems/telegram-bot-0.13.0/lib/telegram/bot/updates_controller.rb:105:in `dispatch'
/coins/gems/gems/telegram-bot-0.13.0/lib/telegram/bot/updates_poller.rb:91:in `process_update'
/coins/gems/gems/telegram-bot-0.13.0/lib/telegram/bot/updates_poller.rb:82:in `block (2 levels) in process_updates'
/coins/gems/gems/telegram-bot-0.13.0/lib/telegram/bot/updates_poller.rb:80:in `each'
```

Could you fix this bugs? Thank.

**Comment by boggddan** [comment]
@printercu, Thank's for you reply.
But, if I want change  to bot message. What do it do?

This example don't work

```ruby
def message(message)
    p "chat_id: #{message['chat']['id']}"
    p "message_id: #{message['message_id']}"

    bot.edit_message_text(chat_id: message['chat']['id'], message_id: message['message_id'], text: "edited message" )
```

```
 Update: {"update_id":113528572,"message":{"message_id":469,"from":{"id":536172205,"is_bot":false,"first_name":"Богдан","username":"b360124","language_code":"ru"},"chat":{"id":536172205,"first_name":"Богдан","username":"b360124","type":"private"},"date":1526570723,"text":"dgfdgd"}}
"chat_id: 536172205"
"message_id: 469"
Completed in 53ms
Bad Request: Bad Request: message can't be edited
/coins/gems/gems/telegram-bot-0.13.0/lib/telegram/bot/client.rb:64:in `request'
/coins/gems/gems/telegram-bot-0.13.0/lib/telegram/bot/async.rb:156:in `request'
/coins/gems/gems/telegram-bot-0.13.0/lib/telegram/bot/client/api_helper.rb:22:in `block (2 levels) in define_helpers'
/coins/app/controllers/telegram/webhook_controller.rb:25:in `message'
/coins/gems/gems/actionpack-5.2.0/lib/abstract_controller/base.rb:194:in `process_action'
```

Thanks

**Comment by printercu** [comment]
Which message do you want to update? You see that in update is your message (`"first_name":"Богдан","username":"b360124"`). Telegram doesn't allow editing it. It's absolutely impossible.

**Comment by boggddan** [comment]
Thanks, I'm understood. You bot is very good.
