### ISSUE TITLE
[bugs] CallbackQueryContext and TypedUpdate together execute error

### ISSUE THREAD

**Issue by boggddan** [telegram-bot-rb/telegram-bot#82]
Hi,
If I include  module `Telegram::Bot::UpdatesController::TypedUpdate` and I run callback, appear error

```ruby
class Telegram::WebhookController < Telegram::Bot::UpdatesController
  include Telegram::Bot::UpdatesController::CallbackQueryContext
  include Telegram::Bot::UpdatesController::TypedUpdate

  def settings(*)
    button = Telegram::Bot::Types::InlineKeyboardButton.new(
      text: "🔄 Refresh  settings",
      callback_data: 'refresh_settings:', url: '')
    markup = Telegram::Bot::Types::InlineKeyboardMarkup.new(inline_keyboard: [[button]])

    respond_with :message, text: 'Settings', reply_markup: markup.to_hash
  end

  def callback_query(data)
    respond_with :message, text: 'callback_query'
  end

  def refresh_settings_callback_query(*)
    respond_with :message, text: 'refresh_settings_callback_query'
  end
end
```

error:
```
Processing by Telegram::WebhookController#refresh_settings_callback_query
  Update: {"update_id":113528908,"message":null,"edited_message":null,"channel_post":null,"edited_channel_post":null,"inline_query":null,"chosen_inline_result":null,"callback_query":{"id":"2302842089460325371","from":{"id":536172205,"is_bot":false,"first_name":"Богдан","last_name":null,"username":"b360124","language_code":"ru"},"message":{"message_id":717,"from":{"id":487597068,"is_bot":true,"first_name":"RealityCoinsTestBot","last_name":null,"username":"RealityCoinsTestBot","language_code":null},"date":1526657337,"chat":{"id":536172205,"type":"private","title":null,"username":"b360124","first_name":"Богдан","last_name":null,"all_members_are_administrators":null,"photo":null,"description":null,"invite_link":null,"pinned_message":null},"forward_from":null,"forward_from_chat":null,"forward_from_message_id":null,"forward_signature":null,"forward_date":null,"reply_to_message":null,"edit_date":null,"author_signature":null,"text":"Settings","entities":[],"audio":null,"document":null,"game":null,"photo":[],"sticker":null,"video":null,"voice":null,"video_note":null,"caption":null,"contact":null,"location":null,"venue":null,"new_chat_members":[],"left_chat_member":null,"new_chat_title":null,"new_chat_photo":[],"delete_chat_photo":null,"group_chat_created":null,"supergroup_chat_created":null,"channel_chat_created":null,"migrate_to_chat_id":null,"migrate_from_chat_id":null,"pinned_message":null,"invoice":null,"successful_payment":null},"inline_message_id":null,"chat_instance":"3425995632556772417","data":"refresh_settings:","game_short_name":null},"shipping_query":null,"pre_checkout_query":null}
Responded with message
Completed in 4ms
undefined method `chat' for #<Telegram::Bot::Types::CallbackQuery:0x000055ae05191eb0>
/coins/gems/gems/virtus-1.0.5/lib/virtus/instance_methods.rb:96:in `public_send'
/coins/gems/gems/virtus-1.0.5/lib/virtus/instance_methods.rb:96:in `[]'
/coins/gems/gems/telegram-bot-0.13.0/lib/telegram/bot/updates_controller.rb:160:in `block in chat'
/coins/gems/gems/activesupport-5.2.0/lib/active_support/core_ext/object/try.rb:16:in `try!'
/coins/gems/gems/telegram-bot-0.13.0/lib/telegram/bot/updates_controller.rb:160:in `chat'
/coins/gems/gems/telegram-bot-0.13.0/lib/telegram/bot/updates_controller/reply_helpers.rb:11:in `respond_with'
/coins/gems/gems/telegram-bot-0.13.0/lib/telegram/bot/updates_controller/instrumentation.rb:40:in `block in respond_with'
/coins/gems/gems/activesupport-5.2.0/lib/active_support/notifications.rb:168:in `block in instrument'
/coins/gems/gems/activesupport-5.2.0/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/coins/gems/gems/activesupport-5.2.0/lib/active_support/notifications.rb:168:in `instrument'
```
Thanks.

**Comment by printercu** [comment]
Thank you. I see the problem, but don't know what is the best way to fix it. Don't want neither add types-related code to `UpdatesController` nor duplicate `chat` to `TypedUpdate`

**Comment by printercu** [comment]
Please try master.
